
struct ConnectData
{
    float4 color        : COLOR0;
};


struct Fragout
{
    float4 col : COLOR0;
};


//-----------------------------------------------------------------------------
// Main
//-----------------------------------------------------------------------------
Fragout main( ConnectData IN )
{
   Fragout OUT;

   // Vert Position
   
   // Base Texture
   //OUT.col = tex2D(diffuseMap, IN.texCoord);
   
   OUT.col = IN.color;
   //OUT.col = float4(0.0f, 1.0f, 0.0f, 1.0f);

   return OUT;
}
