//*****************************************************************************
// Torque -- HLSL procedural shader
//*****************************************************************************

// Dependencies:
#include "shaders/common/lighting.hlsl"
//------------------------------------------------------------------------------
// Autogenerated 'Light Buffer Conditioner [RGB]' Uncondition Method
//------------------------------------------------------------------------------
inline void autogenUncondition_bde4cbab(in float4 bufferSample, out float3 lightColor, out float NL_att, out float specular)
{
   lightColor = bufferSample.rgb;
   NL_att = dot(bufferSample.rgb, float3(0.3576, 0.7152, 0.1192));
   specular = max(bufferSample.a / NL_att, 0.00001f);
}


#include "shaders/common/torque.hlsl"

// Features:
// Vert Position
// Texture Animation
// Parallax
// Base Texture
// Diffuse Color
// Bumpmap [Deferred]
// Deferred RT Lighting
// Visibility
// HDR Output
// Translucent ZWrite
// Hardware Instancing

struct ConnectData
{
   float2 texCoord        : TEXCOORD0;
   float3 outNegViewTS    : TEXCOORD1;
   float4 screenspacePos  : TEXCOORD2;
   float visibility      : TEXCOORD3;
   float2 vpos            : VPOS;
};


struct Fragout
{
   float4 col : COLOR0;
};


//-----------------------------------------------------------------------------
// Main
//-----------------------------------------------------------------------------
Fragout main( ConnectData IN,
              uniform float     parallaxInfo    : register(C0),
              uniform sampler2D bumpMap         : register(S0),
              uniform sampler2D diffuseMap      : register(S1),
              uniform float4    diffuseMaterialColor : register(C1),
              uniform float4    rtParams2       : register(C2),
              uniform sampler2D lightInfoBuffer : register(S2)
)
{
   Fragout OUT;

   // Vert Position
   
   // Texture Animation
   
   // Parallax
   float3 negViewTS = normalize( IN.outNegViewTS );
   IN.texCoord.xy += parallaxOffset( bumpMap, IN.texCoord.xy, negViewTS, parallaxInfo );
   
   // Base Texture
   OUT.col = tex2D(diffuseMap, IN.texCoord);
   
   // Diffuse Color
   OUT.col *= diffuseMaterialColor;
   
   // Bumpmap [Deferred]
   
   // Deferred RT Lighting
   float2 uvScene = IN.screenspacePos.xy / IN.screenspacePos.w;
   uvScene = ( uvScene + 1.0 ) / 2.0;
   uvScene.y = 1.0 - uvScene.y;
   uvScene = ( uvScene * rtParams2.zw ) + rtParams2.xy;
   float3 d_lightcolor;
   float d_NL_Att;
   float d_specular;
   lightinfoUncondition(tex2D(lightInfoBuffer, uvScene), d_lightcolor, d_NL_Att, d_specular);
   OUT.col *= float4(d_lightcolor, 1.0);
   
   // Visibility
   fizzle( IN.vpos, IN.visibility );
   
   // HDR Output
   OUT.col = hdrEncode( OUT.col );
   
   // Translucent ZWrite
   
   // Hardware Instancing
   

   return OUT;
}
