// Torque Input Map File
if (isObject(moveMap)) moveMap.delete();
new ActionMap(moveMap);
moveMap.bindCmd(keyboard, "escape", "", "handleEscape();");
moveMap.bindCmd(keyboard, "tab", "commandToServer(\'action\', 0);", "");
moveMap.bind(keyboard, "ctrl h", hideHUDs);
moveMap.bind(keyboard, "alt p", doScreenShotHudless);
moveMap.bind(keyboard, "a", moveleft);
moveMap.bind(keyboard, "d", moveright);
moveMap.bind(keyboard, "left", moveleft);
moveMap.bind(keyboard, "right", moveright);
moveMap.bind(keyboard, "w", moveForward);
moveMap.bind(keyboard, "s", movebackward);
moveMap.bind(keyboard, "up", moveForward);
moveMap.bind(keyboard, "down", movebackward);
moveMap.bindCmd(keyboard, "e", "commandToServer(\'action\', 20);", "");
moveMap.bind(keyboard, "c", movedown);
moveMap.bind(keyboard, "space", jump);
moveMap.bind(keyboard, "lcontrol", doCrouch);
moveMap.bind(keyboard, "lshift", doSprint);
moveMap.bind(keyboard, "f", setZoomFOV);
moveMap.bind(keyboard, "z", toggleZoom);
moveMap.bind(keyboard, "v", toggleFreeLook);
moveMap.bind(keyboard, "alt c", toggleCamera);
moveMap.bindCmd(keyboard, "ctrl k", "commandToServer(\'suicide\');", "");
moveMap.bindCmd(keyboard, "1", "commandToServer(\'action\', 1);", "");
moveMap.bindCmd(keyboard, "2", "commandToServer(\'action\', 2);", "");
moveMap.bindCmd(keyboard, "3", "commandToServer(\'action\', 3);", "");
moveMap.bindCmd(keyboard, "4", "commandToServer(\'action\', 4);", "");
moveMap.bindCmd(keyboard, "5", "commandToServer(\'action\', 5);", "");
moveMap.bindCmd(keyboard, "6", "commandToServer(\'action\', 6);", "");
moveMap.bindCmd(keyboard, "7", "commandToServer(\'action\', 7);", "");
moveMap.bindCmd(keyboard, "8", "commandToServer(\'action\', 8);", "");
moveMap.bindCmd(keyboard, "9", "commandToServer(\'action\', 9);", "");
moveMap.bind(keyboard, "0", unmountWeapon);
moveMap.bindCmd(keyboard, "f1", "commandToServer(\'action\', 11);", "");
moveMap.bindCmd(keyboard, "f2", "commandToServer(\'action\', 12);", "");
moveMap.bindCmd(keyboard, "f3", "commandToServer(\'action\', 13);", "");
moveMap.bindCmd(keyboard, "f4", "commandToServer(\'action\', 14);", "");
moveMap.bindCmd(keyboard, "f5", "commandToServer(\'action\', 15);", "");
moveMap.bindCmd(keyboard, "f6", "commandToServer(\'action\', 16);", "");
moveMap.bindCmd(keyboard, "f7", "commandToServer(\'action\', 17);", "");
moveMap.bindCmd(keyboard, "f8", "commandToServer(\'action\', 18);", "");
moveMap.bindCmd(keyboard, "q", "commandToServer(\'action\', 19);", "");
moveMap.bindCmd(keyboard, "r", "commandToServer(\'action\', 21);", "");
moveMap.bind(keyboard, "alt w", throwWeapon);
moveMap.bind(keyboard, "alt a", tossAmmo);
moveMap.bind(keyboard, "u", toggleMessageHud);
moveMap.bind(keyboard, "pageup", pageMessageHudUp);
moveMap.bind(keyboard, "pagedown", pageMessageHudDown);
moveMap.bind(keyboard, "p", resizeMessageHud);
moveMap.bindCmd(keyboard, "n", "toggleNetGraph();", "");
moveMap.bindCmd(keyboard, "ctrl z", "carjack();", "");
moveMap.bind(mouse0, "xaxis", yaw);
moveMap.bind(mouse0, "yaxis", pitch);
moveMap.bind(mouse0, "button0", mouseFire);
moveMap.bind(mouse0, "button1", altTrigger);
moveMap.bind(mouse0, "zaxis", mouseWheelWeaponCycle);
moveMap.bind(gamepad0, "thumbrx", D, "-0.23 0.23", gamepadYaw);
moveMap.bind(gamepad0, "thumbry", D, "-0.23 0.23", gamepadPitch);
moveMap.bind(gamepad0, "thumblx", D, "-0.23 0.23", gamePadMoveX);
moveMap.bind(gamepad0, "thumbly", D, "-0.23 0.23", gamePadMoveY);
moveMap.bind(gamepad0, "btn_a", jump);
moveMap.bindCmd(gamepad0, "btn_back", "disconnect();", "");
moveMap.bindCmd(gamepad0, "lpov", "toggleLightColorViz();", "");
moveMap.bindCmd(gamepad0, "upov", "toggleDepthViz();", "");
moveMap.bindCmd(gamepad0, "dpov", "toggleNormalsViz();", "");
moveMap.bindCmd(gamepad0, "rpov", "toggleLightSpecularViz();", "");
moveMap.bind(gamepad0, "btn_b", doCrouch);
moveMap.bind(gamepad0, "triggerr", gamepadFire);
moveMap.bind(gamepad0, "triggerl", gamepadAltTrigger);
moveMap.bind(gamepad0, "btn_start", toggleCamera);
moveMap.bind(gamepad0, "btn_x", toggleFirstPerson);
